spring:
  application:
    name: eureka-server-register

server:
  port: 8760

eureka:
  server:
    # 关闭注册中心的保护机制
    enable-self-preservation: false
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
