spring:
  application:
    name: eureka-server-register2

server:
  port: 8762

eureka:
  client:
    # 由于该应用为注册中心,所以设置为false,代表不向注册中心注册自己
#    register-with-eureka: false
    #由于注册中心的职责就是维护服务实例,它并不需要去检索服务,所以也设置为false
    # fetch-registry: false
    service-url:
      # ,http://localhost:8760/eureka/
      default-zone: http://localhost:8761/eureka/,http://localhost:8763/eureka/
  server:
    # 关闭注册中心的保护机制
    enable-self-preservation: false
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

